### PR TITLE
XIVY-14543 Fix basic authentication

### PR DESCRIPTION
**Pull request by alexsuter**
We no longer an appropriate www-authenticate header. Therefore the JDK Client can not handle this automatically. 

This would be the first use case where we may need this header if we want so support that. If we want that, then I would need to change the core and let the client send a header to not receive www-authenticate headers.

Please share your opinion if this is fine and we can go with this solution or if I should rather change the implementation in the core.
@ivy-rew @ivy-cst @ivy-lli

### CODE REVIEW

**Review by ivy-lli — COMMENTED** [review]
As this breaks every API client in rest calls (so they will be able to use the default auth API), I think it would be better to follow the standard by default and with an additional header which can prevent this www-auth stuff.

ps: revert vscode changes?

**Comment by alexsuter** [comment]
I really don't know why is VSCode toching the Eclipse files :( this happens all the time to me

**Comment by ivy-lli** [comment]
> I really don't know why is VSCode toching the Eclipse files :( this happens all the time to me

comes from the java plugins/extensions, but I also don't know if this changes can be prevented or maybe we just should check them in so we can also edit this files in vscode without have to revert this changes over and over again.

**Comment by ivy-rew** [comment]
> We no longer an appropriate www-authenticate header. Therefore the JDK Client can not handle this automatically.
> 
> This would be the first use case where we may need this header if we want so support that. If we want that, then I would need to change the core and let the client send a header to not receive www-authenticate headers.
> 
> Please share your opinion if this is fine and we can go with this solution or if I should rather change the implementation in the core. @ivy-rew @ivy-cst @ivy-lli

I think sending the header still has no big benefit. As soon as we switch to a more up-2-date authentication scenario, such as OAuth2, the header won't help us anyway. So IMHO it's ok to enforce an eager header to be sent with the request. 

The only field where I really see a benefit, is for requests towards simple test-environments, ...e.g. Swaggers' OpenAPI browser now no longer shows the auth-challenge automatically. But I think we can live with that and better improve this UI rather than sending this header to everyone.

**Comment by alexsuter** [comment]
I can live with both solutions.

**Comment by ivy-lli** [comment]
Even if the chances aren't high there is a possibility that we break code from someone which uses a java client like the web-tester does it now.
However we currently know where we don't want to have this www-auth header, so we can disable it there...

I also can live with both solutions, but lean more in the standard way and do not break.

**Comment by alexsuter** [comment]
After talking to Reguel, we came to following conclusion. Both solutions are valid. 

1. Solution may break clients if they have used this feature with an authenticator. 
2. Solution is more complex and we need to explain how it works

Reguel and myself wouldn't have implemented it out of our heads with the Authenticator approach and would have sent the basic auth egarly. We don't belife that there are many Java clients out-there (or any other). The future solution is anyway to implement a token endpoint and use the bearer approach and turn of the basic auth in general.

Wondering how the mobile app is implemented :) (will ask them)

We can move to both solutions really quick, if we think one of those solutions are not good enough.

Let's go with the less complex solution. If this is a pain in the world, I can switch back quickly.

**Comment by ivy-lli** [comment]
> After talking to Reguel, we came to following conclusion. Both solutions are valid.
> 
>     1. Solution may break clients if they have used this feature with an authenticator.
> 
>     2. Solution is more complex and we need to explain how it works
> 
> 
> Reguel and myself wouldn't have implemented it out of our heads with the Authenticator approach and would have sent the basic auth egarly. We don't belife that there are many Java clients out-there (or any other). The future solution is anyway to implement a token endpoint and use the bearer approach and turn of the basic auth in general.
> 
> Wondering how the mobile app is implemented :) (will ask them)
> 
> We can move to both solutions really quick, if we think one of those solutions are not good enough.
> 
> Let's go with the less complex solution. If this is a pain in the world, I can switch back quickly.

thx for documentation, maybe we should also add this discussion to the jira issue :)

**Pull request merged**
